### ISSUE TITLE
migrate tests to githubactions

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#18]
migrate tests to githubactions

**Comment by stamepicmorg** [comment]
facepunch example
```
name: Build All

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Win64
      run: dotnet restore Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj
    - name: Restore Win32
      run: dotnet restore Facepunch.Steamworks\Facepunch.Steamworks.Win32.csproj
    - name: Restore Posix
      run: dotnet restore Facepunch.Steamworks\Facepunch.Steamworks.Posix.csproj
      
    - name: Build Win64
      run: msbuild Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj
    - name: Build Win32
      run: msbuild Facepunch.Steamworks\Facepunch.Steamworks.Win32.csproj
    - name: Build Posix
      run: msbuild Facepunch.Steamworks\Facepunch.Steamworks.Posix.csproj

    - uses: actions/upload-artifact@v1
      with:
        name: Compiled Files
        path: Facepunch.Steamworks/bin
```
